import React from 'react'

function page() {
    return (
        <div className='mx-auto container'>
            <div className='px-20 pb-20 pt-10 space-y-10 font-serif'>
                <p className='text-2xl font-bold'>Terms And Conditions</p>

                <p><span className='font-semibold mr-1'>A.</span>{""}
                    This document is an electronic record in terms of Information
                    Technology Act, 2000 and rules there under as applicable and the
                    amended provisions pertaining to electornic records in various statutes as
                    amended by the Information Technology Act, 2000. This electronic record is
                    generated by a computer system and does not require any physical or
                    digital signatures.
                </p>

                <p><span className='font-semibold mr-1'>B.</span>{""}
                    This document is published in accordance with the provisions of Rule
                    3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011
                    that require publishing the rules and regulations, privacy policy and terms
                    of use for access or usage of domain name www.zlshealth.com (&quot;Website&quot;), including
                    the related mobile site and mobile application (hereinafter referred to as &quot;Platform&quot;).
                </p>

                <p><span className='font-semibold mr-1'>C.</span>{" "}
                    The Platform is owned by ZEALOUS HEALTH PRIVATE LIMITED, a
                    company incorporated under the Companies Act, 1956 with its
                    registered office at ZEALOUS HEALTH PRIVATE LIMITED H.No.2-14/2,
                    Survey No.312, Narsingi, Rajendranagar, Rangareddi, Telengana-500089
                    (hereinafter referred to as &quot;Platform Owner&quot;, &quot;we&quot;, &quot;us&quot;, &quot;our&quot;).
                </p>

                <p><span className='font-semibold mr-1'>D.</span>{" "}
                    Your use of the Platform and services and tools are governed by the
                    following terms and conditions (&quot;Terms of Use&quot;) as applicable to the
                    Platform including the applicable policies which are incorporated herein
                    by way of reference. If you transact on the Platform, You shall be subject
                    to the policies that are applicable to the Platform for such transaction. By
                    mere use of the Platform, You shall be contracting with the Platform Owner and these
                    terms and conditions including the policies constitute Your binding obligations, with Platform Owner.
                    These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable)
                    (collectively, &quot;Services&quot;). Any terms and conditions proposed by You which are in addition
                    to or which conflict with these Terms of Use are expressly rejected by the Platform Owner
                    and shall be of no force or effect. These Terms of Use can be modified at any time without
                    assigning any reason. It is your responsibility to periodically review these Terms of Use
                    to stay informed of updates.
                </p>

                <p><span className='font-semibold mr-1'>E.</span>
                    For the purpose of htese Terms of Use, wherever the context so requires &quot;you&quot;, &quot;your&quot; or
                    &quot;user&quot; shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
                </p>

                <p><span className='font-semibold mr-1'>F.</span>
                    ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS
                    AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
                </p>

                <p><span className='font-semibold mr-1'>G.</span>
                    The use of Platform and/or availing of our Services is subject to the following
                    Terms of Use:
                </p>

                <div className='space-y-5'>
                    <p><span className='font-semibold'>I.</span> To acces and use the Services, you agree to provide true, accurate
                        and complete information to us during and after registration, and you
                        shall be responsible for all acts done through the use of your registered
                        account on the Platform.
                    </p>

                    <p>
                        <span className='font-semibold'>II.</span> Neither we nor any third parties provide an warranty or guarantee as
                        to the accuracy, timeliness, performance, completeness or suitablility of
                        the information and materials offered on this website or through the Services,
                        for any specific purpose. You acknowledge that such information and materials may contain
                        inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors
                        to the fullest extent permitted by law.
                    </p>
                    <p>
                        <span className='font-semibold'>III.</span> Your use of our Services and the Platform is solely and entirely at your
                        own risk and discretion for which we shall not be liable to you in any manner.
                        You are required to independently assess and ensure that the Services meet your requirements.
                    </p>

                    <p>
                        <span className='font-semibold'>IV.</span> The contents of the Platform and the Services are proprietary to us
                        and are licensed to us. You will not have authority to claim any intellectual
                        property rights, title, or interest in its contents. The contents includes and is
                        not limited to the design, layout, look and graphics.
                    </p>

                    <p>
                        <span className='font-semibold'>V.</span> You acknowledge that unauthorized use of the Platform and/or the Services may lead
                        to action against you as per these Terms of Use and/or applicable laws.
                    </p>

                    <p>
                        <span className='font-semibold'>VI.</span> You agree to pay us the charges associated with availing the Services.
                    </p>

                    <p>
                        <span className='font-semibold'>VII.</span> You agree not to use the Platform and/or Services for any purpose that is
                        unlawful, illegal or forbidden by these Terms, or Indian or local laws that might
                        apply to you.
                    </p>

                    <p>
                        <span className='font-semibold'>VIII.</span> You agree and acknowledge that website and the Services may contain
                        links to other third party websites. On accessing these links, you will be governed
                        by the terms of use, privacy policy and such other policies of such third party websites.
                        These links are provided for your convenience for provide further information.
                    </p>

                    <p>
                        <span className='font-semibold'>IX.</span> You understand that upon initiating a transaction for availing the Services your are
                        entering into a legally binding and enforceable contract with the Platform Owner for the Services.
                    </p>

                    <p>
                        <span className='font-semibold'>X.</span> You shall indemnify and hold harmlesss Platform Owner, its affiliates, group companies (as applicable) and their
                        respective officers, directors, agents, and employees, from any clain or demand, or actions including
                        reasonable attorneys&apos; fees, made by any third party or penalty imposed due to or arising out of your breach
                        of this Terms of Use, privacy policy and other policies, or you violation of any law, rules or
                        regulations or the rights (including infringement of intellectual property rights) of a third party.
                    </p>

                    <p>
                        <span className='font-semibold'>XI.</span> In no event will the Platform Owner be liable for any indirect, consequential, incidental,
                        apecial or punitive damages, including without limitations damages for loss of proits or revenues,
                        business interruption, loss of business opportunities, loss of data or loss of other economic interests,
                        whether in contract, negligence, tort or otherwise, arising from the use of or inabiliity to use the Services,
                        however caused and whether arising in contract, tort, negligence, warranty or otherwise, exceed the amount
                        paid by you for using th eservices giving rise to the cause of action or Rupees One Hundred (Rs. 100) whichever
                        is less.
                    </p>

                    <p>
                        <span className='font-semibold'>XII.</span> Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any
                        failure to perform an obligation under these terms if performance is prevented or delayed by a force
                        majeur event.
                    </p>

                    <p>
                        <span className='font-semibold'>XIII.</span> These terms and any dispute or claim relating to it, or its enforceability, shall be
                        governed by and construed in accordance with the laws of India.
                    </p>

                    <p>
                        <span className='font-semibold'>XIV.</span> All disputes arising out of or in connection with these terms shall be
                        communicated to us using the contact information provided on this website.
                    </p>

                    <p>
                        <span className='font-semibold'>XV.</span> All concerns or communications relating to these terms must be
                        communicated to us using the contact information provided on this website.
                    </p>
                </div>

                <p>
                    <span className="font-bold">Note: </span>{" "}
                    Customers purchasing sexually wellness products must confirm that they are
                    <span className='font-bold'> above 18 years of age </span> at the time of purchase.
                </p>
            </div>
        </div>
    )
}

export default page